package com.absolutex.core.data

import androidx.room.AutoMigration
import androidx.room.Dao
import androidx.room.Database
import androidx.room.Entity
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.PrimaryKey
import androidx.room.Query
import androidx.room.RoomDatabase
import kotlinx.coroutines.flow.Flow

@Entity(tableName = "reading_progress")
data class ReadingProgress(
    @PrimaryKey val bookId: String,
    val pageIndex: Int,
    val pageCount: Int,
    /** Epoch millis. §5.5 sync is last-write-wins, so every row carries its own timestamp. */
    val updatedAt: Long,
)

@Dao
interface ProgressDao {
    @Query("SELECT * FROM reading_progress WHERE bookId = :bookId")
    suspend fun get(bookId: String): ReadingProgress?

    @Query("SELECT * FROM reading_progress WHERE bookId = :bookId")
    fun observe(bookId: String): Flow<ReadingProgress?>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsert(progress: ReadingProgress)

    @Query("SELECT * FROM reading_progress ORDER BY updatedAt DESC LIMIT 1")
    suspend fun mostRecent(): ReadingProgress?

    /**
     * Every stored position, for the library's Reading and Unread shelves (§5.1).
     *
     * A whole-table read rather than one lookup per book: the library renders thousands of rows
     * and per-book queries would be thousands of round trips per scan. The table holds one row
     * per book ever opened, so it stays far smaller than the library itself. Joined on
     * BookIdentity, which since 6f7d70d is the key both this table and library_book use.
     */
    @Query("SELECT * FROM reading_progress")
    fun observeAll(): Flow<List<ReadingProgress>>
}

/**
 * Version 2 adds the library table. An AutoMigration handles it because adding a table needs no
 * data rewrite — and a destructive fallback would throw away the user's reading position, which
 * is the one thing in here that cannot be regenerated by rescanning. Version 3 adds bookmarks and
 * version 4 per-book overrides, the same way and for the same reason. Version 6 adds reading
 * history ([PageView]), which is the same shape again: a new table, nothing rewritten, and
 * nothing a rescan could rebuild if it were dropped.
 */
@Database(
    entities = [
        ReadingProgress::class, LibraryBook::class, Bookmark::class, BookPrefs::class,
        PageView::class,
    ],
    version = 7,
    exportSchema = true,
    autoMigrations = [
        AutoMigration(from = 1, to = 2),
        AutoMigration(from = 2, to = 3),
        AutoMigration(from = 3, to = 4),
        AutoMigration(from = 4, to = 5),
        AutoMigration(from = 5, to = 6),
        AutoMigration(from = 6, to = 7),
    ],
)
abstract class AbsolutexDatabase : RoomDatabase() {
    abstract fun progressDao(): ProgressDao
    abstract fun libraryDao(): LibraryDao
    abstract fun bookmarkDao(): BookmarkDao
    abstract fun bookPrefsDao(): BookPrefsDao
    abstract fun pageViewDao(): PageViewDao
}
