package com.absolutex.core.data

import androidx.room.AutoMigration
import androidx.room.Dao
import androidx.room.Database
import androidx.room.Entity
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.PrimaryKey
import androidx.room.Query
import androidx.room.RoomDatabase
import kotlinx.coroutines.flow.Flow

@Entity(tableName = "reading_progress")
data class ReadingProgress(
    @PrimaryKey val bookId: String,
    val pageIndex: Int,
    val pageCount: Int,
    /** Epoch millis. §5.5 sync is last-write-wins, so every row carries its own timestamp. */
    val updatedAt: Long,
)

@Dao
interface ProgressDao {
    @Query("SELECT * FROM reading_progress WHERE bookId = :bookId")
    suspend fun get(bookId: String): ReadingProgress?

    @Query("SELECT * FROM reading_progress WHERE bookId = :bookId")
    fun observe(bookId: String): Flow<ReadingProgress?>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsert(progress: ReadingProgress)

    @Query("SELECT * FROM reading_progress ORDER BY updatedAt DESC LIMIT 1")
    suspend fun mostRecent(): ReadingProgress?

    /**
     * Every stored position, for the library's Reading and Unread shelves (§5.1).
     *
     * A whole-table read rather than one lookup per book: the library renders thousands of rows
     * and per-book queries would be thousands of round trips per scan. The table holds one row
     * per book ever opened, so it stays far smaller than the library itself.
     */
    @Query("SELECT * FROM reading_progress")
    fun observeAll(): Flow<List<ReadingProgress>>
}

/**
 * Version 2 adds the library table. An AutoMigration handles it because adding a table needs no
 * data rewrite — and a destructive fallback would throw away the user's reading position, which
 * is the one thing in here that cannot be regenerated by rescanning.
 */
@Database(
    entities = [ReadingProgress::class, LibraryBook::class],
    version = 2,
    exportSchema = true,
    autoMigrations = [AutoMigration(from = 1, to = 2)],
)
abstract class AbsolutexDatabase : RoomDatabase() {
    abstract fun progressDao(): ProgressDao
    abstract fun libraryDao(): LibraryDao
}
