package com.absolutex.core.data

import androidx.room.ColumnInfo
import androidx.room.Dao
import androidx.room.Entity
import androidx.room.Index
import androidx.room.Insert
import androidx.room.PrimaryKey
import androidx.room.Query
import com.absolutex.core.stats.PageSettled
import javax.inject.Inject
import javax.inject.Singleton

/**
 * One page having come to rest in the reader (§4, milestone 7).
 *
 * The whole of reading history is this table. Sessions, time read, streaks and per-series
 * totals are all *derived* from these rows by `:core:stats` — a session is a run of views with
 * no gap longer than the idle threshold, which is a reading of the data rather than a second
 * fact about it. Storing sessions as well would be two sources of truth for one thing, free to
 * disagree the first time the threshold changed or a write was lost.
 *
 * [bookKey] is a `BookIdentity` key, the same one progress, bookmarks and the library use, so a
 * renamed book keeps one history rather than splitting into several.
 *
 * Growth is bounded only by reading: roughly one row per page turned, so a heavy year is tens
 * of thousands of rows and well under a megabyte. There is deliberately no pruning yet —
 * discarding a reader's history to save kilobytes needs a product decision, not a default.
 *
 * Every column carries a default so a later `AutoMigration` that adds one to this table does
 * not need a hand-written migration.
 */
@Entity(
    tableName = "page_view",
    indices = [Index("bookKey"), Index("atEpochMs")],
)
data class PageView(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(defaultValue = "0")
    val id: Long = 0,
    @ColumnInfo(defaultValue = "")
    val bookKey: String,
    @ColumnInfo(defaultValue = "0")
    val page: Int,
    /** Wall-clock millis. Days and streaks are resolved in the reader's zone, never UTC. */
    @ColumnInfo(defaultValue = "0")
    val atEpochMs: Long,
)

/**
 * Reading history is append-only, which is why nothing here upserts.
 *
 * That matters because of the trap `upsertPreservingAddedAt` exists for: `@Insert(REPLACE)`
 * deletes and reinserts, so it clears any column the caller did not resupply. Nothing here can
 * hit it — rows have an autogenerated key, are never rewritten, and carry no field a later
 * write would have to preserve. What *would* have hit it is the obvious optimisation: a
 * per-book totals row updated on every event. That is also the reason not to add one.
 */
@Dao
interface PageViewDao {

    /** Inserts a batch. Suspend, so Room runs it on its own executor rather than the caller's. */
    @Insert
    suspend fun record(views: List<PageView>)

    @Query("SELECT * FROM page_view ORDER BY atEpochMs")
    suspend fun all(): List<PageView>

    /** History from a point in time, for a stats screen that shows a window rather than all of it. */
    @Query("SELECT * FROM page_view WHERE atEpochMs >= :sinceEpochMs ORDER BY atEpochMs")
    suspend fun since(sinceEpochMs: Long): List<PageView>

    @Query("SELECT COUNT(*) FROM page_view")
    suspend fun count(): Int

    /** §4: the user can delete all of it, and that has to mean all of it. */
    @Query("DELETE FROM page_view")
    suspend fun deleteAll()
}

/**
 * Reading history, in the domain's terms rather than the table's.
 *
 * Nothing here leaves the device and nothing here reaches the network: the module has no
 * network dependency at all, which is the point of §4's no-analytics rule rather than a
 * consequence of it.
 *
 * No `withContext`: Room dispatches suspend DAO calls to its own executor, so these are already
 * off the main thread. The house precedent is [LibraryRepository.scanTree], which wraps the
 * filesystem walk and leaves the DAO calls outside it.
 *
 * [record] takes a batch because the reader must not write once per settled page on the draw
 * path. How large a batch and when to flush is the call site's policy, not this layer's — the
 * emit hook lives in the reader.
 */
@Singleton
class ReadingHistory @Inject constructor(private val views: PageViewDao) {

    suspend fun record(events: List<PageSettled>) {
        if (events.isEmpty()) return
        views.record(events.map { PageView(bookKey = it.bookKey, page = it.page, atEpochMs = it.atEpochMs) })
    }

    suspend fun history(): List<PageSettled> = views.all().map(PageView::toSettled)

    suspend fun historySince(epochMs: Long): List<PageSettled> =
        views.since(epochMs).map(PageView::toSettled)

    suspend fun pagesRecorded(): Int = views.count()

    /** Forgets everything. There is no soft delete: §4 says the user owns this. */
    suspend fun forget() {
        views.deleteAll()
    }
}

private fun PageView.toSettled() = PageSettled(bookKey = bookKey, page = page, atEpochMs = atEpochMs)
